# Generated by Django 4.1 on 2022-08-03 13:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("orbs", "0002_remove_thread_original_poster"),
    ]

    operations = [
        migrations.AddField(
            model_name="board",
            name="abbreviation",
            field=models.CharField(default="", max_length=15),
            preserve_default=False,
        ),
    ]
