# Generated by Django 4.0.4 on 2022-04-30 00:12

from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone
import model_utils.fields
import uuid


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Category',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=63)),
            ],
        ),
        migrations.CreateModel(
            name='Board',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created', model_utils.fields.AutoCreatedField(default=django.utils.timezone.now, editable=False, verbose_name='created')),
                ('modified', model_utils.fields.AutoLastModifiedField(default=django.utils.timezone.now, editable=False, verbose_name='modified')),
                ('uuid', models.UUIDField(default=uuid.uuid4, editable=False)),
                ('name', models.CharField(max_length=63, verbose_name='name')),
                ('description', models.CharField(max_length=255, verbose_name='description')),
                ('slug', models.CharField(max_length=3, verbose_name='slug')),
                ('category', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='boards', to='boards.category')),
            ],
            options={
                'abstract': False,
            },
        ),
    ]
