# Generated by Django 4.0.4 on 2022-04-30 00:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('boards', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='category',
            options={'verbose_name_plural': 'Categories'},
        ),
        migrations.AlterField(
            model_name='board',
            name='slug',
            field=models.CharField(max_length=31, verbose_name='slug'),
        ),
    ]
